---
title: "Data Preprocessing"
author: "Alexander Kleine"
date: "6/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
library(tidyverse)
library(readxl)
```

Reading in the DF
```{r}
diary_AMV <- read_excel("Music Test Data/diary_AMV.xlsx")
diary_AMV <- diary_AMV[,c(1,7:16)]
diary_AMV <- data.frame(lapply(diary_AMV[,1:11], as.character), stringsAsFactors=FALSE)
str(diary_AMV)
```

#Data Preprocessing
```{r}
str(diary_AMV)
vector_test <- as.integer(as.vector(diary_AMV[[1,2]]))
str_length(vector_test)
str_sub(vector_test, 1, 1)
```

```{r}
diary_AMV_sep <- diary_AMV


for (u in 1:120) {
  for (i in 2:11) {
    diary_AMV_sep[u,i] <- gsub("^,|,$", "", gsub("\\b", ",", diary_AMV_sep[u,i]))
  }
}
rm(i)
rm(u)
```

##Song Values
Each value is representing as a character 5 different songs. One row stands then for 50 Songs in a interval-based rating
```{r}
first_df <- as.data.frame(diary_AMV_sep[,2], stringsAsFactors = FALSE)
all_songs <- first_df %>% separate(1, c("1", "2", "3", "4", "5"))


for (i in 3:11) {
  new_one <- as.data.frame(diary_AMV_sep[,i], stringsAsFactors = FALSE)
  new_one <- new_one %>% separate(1, c("1", "2", "3", "4", "5"))
  all_songs <- cbind(all_songs, new_one)
}
rm(i)

for (i in 1:50) {
  colnames(all_songs)[i] <- paste0("SongNr_", i)
}
```

Final DF:
```{r}
user <- as.data.frame(diary_AMV[,1], stringsAsFactors = FALSE)
colnames(user)[1] <- "user"

final_df <- cbind(user, all_songs)
write_csv(final_df, path = "final_df.csv")
```


